name: Deploy on EC2 Dockerhub Images and run Docker Compose

on:
  push:
    branches:
      - main

jobs:

  deploy-dockerhub:
    name: Build and push to Docker Hubs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wisniewskikr/github-actions-redeploy-java-dockercompose-aws-ec2-dockerhub:latest
  
  deploy-ec2:
    name: Deploy Docker Compose script to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_URL }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SOURCE: scripts
          TARGET: /home/ec2-user
          
  run-ec2:
    name: Run Docker Compose commands on EC2
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/scripts
            docker-compose pull
            docker-compose up -d